<?php

include("../lib/default_config.php");


if ( $_REQUEST['image'] && $_REQUEST['device'] && $_REQUEST['filename'] && $_REQUEST['type'] && $_REQUEST['blog_id'] ) {

	$id = add_data($_REQUEST['type'], base64_decode($_REQUEST['image']));
	$_REQUEST['image'] = NULL;

	$data[$_REQUEST['type']] = array("type"=>"local", "dtype"=>$_REQUEST['type'], "id"=>$id,"name"=>$_REQUEST['filename'].".".$_REQUEST['type']);
	$id = add_data_meta($_REQUEST['filename']." - ".date("H:i:s d M y" ,time()), $data);

	$blog_title = "Auto blog - ".$_REQUEST['device'];
	$blog_content = "Auto blog generated by ".$_REQUEST['device']."[data]".$id."[/data]";

	$blog_meta = "<METADATA><DATA>$id</DATA></METADATA>";

	$blog_group = "Auto blog";

	$blog_id = $blog['blog_id'] = $_REQUEST['blog_id'];

	add_blog($blog['blog_id'], $blog_title, $blog_content, $blog_meta, $blog_group, NULL, 'Autoblogger');
	exit();
}

	//PicComets
if (!$_SESSION['user_name']) { exit(); }

if( $_REQUEST['image'] &&  $_REQUEST['postID'] ) {

	$postid = (int)$_REQUEST['postID'];

	$newid = add_data("png", base64_decode($_REQUEST['image']));
	$main_data = array("png"=>array("type"=>"local", "id"=>$newid ));
	$newid = add_data_meta($_REQUEST['title'], $main_data, NULL,$postid);

	$sql =	"SELECT  * FROM  `{$ct_config['blog_db']}`.`blog_bits` ";
		$sql .= "WHERE `bit_id` = ".$postid." AND `bit_edit` = 0";

	$tresult = runQuery($sql,'Blogs');

	$row = mysql_fetch_array($tresult);

	$blog_id = $blog['blog_id'] = $row['bit_blog'];

	$metadata = readxml($row['bit_meta']);
	
	if(isset($metadata['METADATA']['DATA'])){
		$metadata['METADATA']['DATA'] .= ",".$newid;
	}else{
		$metadata['METADATA']['DATA'] = $newid;
	}

	$meta = null;
	$metad = writexml($metadata);
	
	$new_id = edit_blog($postid, 'Added Sketch', NULL, NULL, $metad, NULL);
	
}

if ( $_REQUEST['image'] &&  $_REQUEST['originalID']) {

	$originalID = $_REQUEST['originalID'];
	$id = add_data('png', base64_decode($_REQUEST['image']));
	
	$content = "<metadata><title>".date("H:i:s d M y" ,time())."</title><user>".$_SESSION['user_name']."</user><id>$id</id></metadata>";
	$id = add_data('overlay', $content);
	
	$sql = "SELECT * FROM `{$ct_config['blog_db']}`.`blog_data` WHERE `data_id` = $originalID";
	$result = runQuery($sql, 'Select original');
	$row = mysql_fetch_array($result);

	$content = $row['data_data'];
	$expression = "</overlay>";
	if ( strstr($content,$expression) ) { $content = str_ireplace( $expression, ",$id".$expression, $content); }
	else { $content = str_ireplace("</metadata>", "<overlay>$id</overlay></metadata>", $content); }

	echo $sql = "UPDATE `{$ct_config['blog_db']}`.`blog_data` SET `data_data` = '".addSlashes($content)."' WHERE `data_id` = '$originalID'";
	runQuery($sql, 'Update original');

	echo 1;

}

?>
