<?php

include("../default_config.php");

$htaccess = <<<HTACCESS
# automatically generated by htaccess.php
DirectoryIndex index.php

RewriteEngine on

RewriteBase {$ct_config['blog_path']}uri
RewriteCond %{REQUEST_URI} ^{$ct_config['blog_path']}uri
RewriteCond %{REQUEST_URI} !\.php
RewriteRule ^(.+)$ {$ct_config['blog_path']}uri/index.php?uri=$1 [L,QSA]

RewriteBase {$ct_config['blog_path']}data/files
RewriteCond %{REQUEST_URI} ^{$ct_config['blog_path']}data/files
RewriteCond %{REQUEST_URI} !\.php
RewriteRule files\/(.*)$ {$ct_config['blog_path']}getdata.php?uri=$1 [L,QSA]

RewriteBase {$ct_config['blog_path']}data
RewriteCond %{REQUEST_URI} ^{$ct_config['blog_path']}data
RewriteCond %{REQUEST_URI} !\.php
RewriteRule ^(.*)$ {$ct_config['blog_path']}data_pre.php?uri=$1 [L,QSA]

RewriteBase {$ct_config['blog_path']}user
RewriteCond %{REQUEST_URI} ^{$ct_config['blog_path']}user
RewriteCond %{REQUEST_URI} !\.php
RewriteCond %{REQUEST_URI} !^{$ct_config['blog_path']}style
RewriteCond %{REQUEST_URI} !^{$ct_config['blog_path']}inc
RewriteCond %{REQUEST_URI} !^{$ct_config['blog_path']}feeds
RewriteCond %{REQUEST_URI} !^{$ct_config['blog_path']}admin
RewriteCond %{REQUEST_URI} !^{$ct_config['blog_path']}uri
RewriteCond %{REQUEST_URI} !^{$ct_config['blog_path']}java
RewriteRule ^(.+)$ {$ct_config['blog_path']}user.php?uri=$1 [L,QSA]

RewriteBase {$ct_config['blog_path']}feeds
RewriteCond %{REQUEST_URI} ^{$ct_config['blog_path']}feeds
RewriteCond %{REQUEST_URI} !\.php
RewriteRule ^(.*)$ {$ct_config['blog_path']}feeds.php?uri=$1 [L,QSA]

RewriteBase {$ct_config['blog_path']}search
RewriteCond %{REQUEST_URI} ^{$ct_config['blog_path']}search
RewriteCond %{REQUEST_URI} !\.php
RewriteRule ^(.*)$ {$ct_config['blog_path']}search.php?uri=$1 [L,QSA]

RewriteBase {$ct_config['blog_path']}api/rest
RewriteCond %{REQUEST_URI} ^{$ct_config['blog_path']}api/rest
RewriteCond %{REQUEST_URI} !\.php
RewriteRule ^(.*)$ {$ct_config['blog_path']}api/rest/rest.php?uri=$1 [L,QSA]

RewriteBase {$ct_config['blog_path']}
RewriteRule ^odata/(.+) {$ct_config['blog_path']}export/sp_odata.php?uri=$1 [L,QSA]
RewriteRule ^(.+)/sitemap\.xml\.gz\$ /sitemaps/\$1.xml.gz
RewriteCond %{REQUEST_URI} ^{$ct_config['blog_path']}

HTACCESS;

foreach($ct_config['protected_paths'] as $val)
$htaccess .= "RewriteCond %{REQUEST_URI} !^{$ct_config['blog_path']}{$val}\n";

$htaccess .= <<<HTACCESS
RewriteCond %{REQUEST_URI} !\.php
RewriteCond %{REQUEST_URI} !\.class
RewriteCond %{REQUEST_URI} !\.txt
RewriteCond %{REQUEST_URI} !^/sitemap.xml
RewriteCond %{REQUEST_URI} !\.xml\.gz
RewriteCond %{REQUEST_URI} !\.(js|css|gif|ico)
RewriteCond %{REQUEST_URI} !{$ct_config['blog_path']}cache/.*\.zip$
RewriteRule ^(.+)\$ {$ct_config['blog_path']}blog.php?uri=\$1 [L,QSA]

HTACCESS;

file_put_contents("../../docs/.htaccess",$htaccess);

?>
